on:
  workflow_dispatch: {}
  pull_request: {}
  push: {}  # Será acionado em qualquer push no repositório
name: Semgrep
jobs:
  semgrep:
    name: semgrep/ci
    runs-on: self-hosted
    env:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
    container:
      image: returntocorp/semgrep
    steps:
    - uses: actions/checkout@v3
    - name: Executar Semgrep
      run: semgrep ci --json-output results.json
    - name: Verificar Vulnerabilidades Críticas
      run: |
        # Script para analisar o arquivo de resultados e quebrar a build se encontrar vulnerabilidades críticas
        cat results.json
        jq '.results[] | select(.extra.severity == "ERROR")' results.json > critical_results.json
        if [ -s critical_results.json ]; then
          echo "Vulnerabilidades críticas encontradas."
          exit 1
        fi
